#+TITLE: Journal 3-2
#+AUTHOR: Ankur Mishra
#+DATE: February 2018
* Timeline
* Progress
This week I continued researching Linear Classification from Karapathy's CS231n Lectures. 
I learned about basic loss functions, such as Multiclass SVM Loss and made my own linear classifier in Python. Here is an excerpt from some notes I took 
while watching his lecture:
** Multiclass SVM Loss
\begin{equation}
L_i = \sum_{j \neq y_i} max(0, s_j - s_y_i + 1)
\end{equation}
$j$ is the object with the highest score. $y_i$ is the object which is trying to be classified.
The loss of the function itself is:
\begin{equation}
L = 1/N  \sum_{i=1}^{N} L_i
\end{equation}
* Project Discussion
Since progress has slowed since I got sick and last week we had vistors, I'm pushing my goal from last week to have a functional object detection algorithm 
by another two weeks. I will also have to work a little outside of class to account for some missed time but I hope to catch up so that I can get closer to my original deadline.
Also, I have to start working on making my code work along side my agent this week.
